### ISSUE TITLE
jejak

### ISSUE THREAD

**Issue by MFarelS** [Terror-Machine/fnbots#34]
nunggu update fitur lagi, xixixix

**Comment by MFarelS** [comment]
Tumtor Imstall?? 

Ntar w donate








 















































































































































































































































































































tapi boong:)

**Comment by MFarelS** [comment]
> tidak tersedia untuk umum. gw cuman bagi share fitur aja. kalo mau di contoh, bisa. tapi buat bagi skrip? kayaknya nanti dulu deh

Ss in fitur nulisnya MhankBarBar xixixi

**Comment by rebahanelite** [comment]
nyimak bang jago

**Comment by MFarelS** [comment]
> maka dari itu. untung gasembarangan sebar sc wkwkwk

Ssin waktu pake sc nulisnya stah

**Comment by MFarelS** [comment]
Iya Tau, Author Aslinya Elianiva, W Mau Ambil Kertasnya Doang, Mau Nambah
BG Awokwaokwaokwaok

Pada tanggal Rab, 4 Nov 2020 11.22, FN <notifications@github.com> menulis:

**Comment by itzngga** [comment]
Tolong klo sebar sc umum gk ush claim2, dah muak gw liat bang jago di luar sana

**Comment by MFarelS** [comment]
> > Iya Tau, Author Aslinya Elianiva, W Mau Ambil Kertasnya Doang, Mau Nambah BG Awokwaokwaokwaok Pada tanggal Rab, 4 Nov 2020 11.22, FN [notifications@github.com](mailto:notifications@github.com) menulis:
> 
> https://github.com/elianiva/img-to-sticker-bot/
> ini originnya

Iya tau, cuman mao bage kertasnya Awokwaokwaokwaok

**Comment by MFarelS** [comment]
> > > Iya Tau, Author Aslinya Elianiva, W Mau Ambil Kertasnya Doang, Mau Nambah BG Awokwaokwaokwaok Pada tanggal Rab, 4 Nov 2020 11.22, FN [notifications@github.com](mailto:notifications@github.com) menulis:
> > 
> > 
> > https://github.com/elianiva/img-to-sticker-bot/
> > ini originnya
> 
> Iya tau, cuman mao bage kertasnya Awokwaokwaokwaok

*minta

**Comment by MFarelS** [comment]
Dah Neh Mhank @Terror-Machine 
https://github.com/MFarelS/RajinNulis-BOT
Ntar Magernulis 2:v
